# Generated by Django 3.0.8 on 2023-07-24 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helloreport', '0004_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_no', models.CharField(max_length=20)),
                ('quotation_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(max_length=20)),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloreport.Customers')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloreport.Product')),
            ],
        ),
    ]
