# Generated by Django 3.0.8 on 2023-07-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloreport', '0006_addsupplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_purchase_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_sale_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
