# Generated by Django 3.0.8 on 2023-07-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloreport', '0008_auto_20230728_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='purchase',
        ),
    ]
