# Generated by Django 3.0.8 on 2023-07-28 16:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('helloreport', '0009_remove_sale_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='purchase',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='helloreport.Purchase'),
            preserve_default=False,
        ),
    ]
